project:
  # TODO: change to extension name if using a custom extension
  type: seedcase-theme

website:
  # TODO: Fill in the title of the website.
  title: "Seedcase Flower"
  # TODO: Set the Netlify custom domain URL
  site-url: "https://flower.seedcase-project.org"
  repo-url: "https://github.com/seedcase-project/seedcase-flower"
  page-navigation: true
  navbar:
    pinned: true
    title: false
    logo: "_extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-flower.svg"
    logo-alt: "seedcase flower logo: Main page"
    left:
      - text: "Overview"
        href: docs/index.qmd
      - text: "Guide"
        href: docs/guide/index.qmd
      - text: "Design"
        href: docs/design/index.qmd
      # - text: "Reference"
      #   href: docs/reference/index.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-flower"
        aria-label: "GitHub icon: Source code"
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Main website for the Seedcase Project"
  sidebar:
    - id: overview
      pinned: true
      style: "floating"
      contents:
        - docs/index.qmd
        - CHANGELOG.qmd
        - CONTRIBUTING.md
    - id: design
      contents:
        - text: "Design"
          href: docs/design/index.qmd
    - id: guide
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd

quartodoc:
  sidebar: "docs/reference/_sidebar.yml"
  style: "pkgdown"
  dir: "docs/reference"
  package: "seedcase_flower"
  parser: google
  dynamic: true
  renderer:
    style: _renderer.py
    table_style: description-list
    show_signature_annotations: true

metadata-files:
  - docs/reference/_sidebar.yml

format:
  seedcase-theme-html:
    theme:
      - brand
    # TODO: Uncomment if using the goatcounter website visitor counter
    # include-before-body:
      # - "docs/includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true
